name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore app/Guidzgo.sln

    - name: Build Release Solution
      run: msbuild app/Guidzgo.sln /p:Configuration=Release
      working-directory: ${{ github.workspace }}

    - name: Build Debug Solution
      run: msbuild app/Guidzgo.sln /p:Configuration=Debug
      working-directory: ${{ github.workspace }}

    - name: Debug Build Output
      run: |
        if (Test-Path app\Guidzgo\bin\Release) {
          Write-Output "Checking Release folder..."
          Get-ChildItem app\Guidzgo\bin\Release
        } else {
          Write-Output "Release folder not found."
        }

        if (Test-Path app\Guidzgo\bin\Debug) {
          Write-Output "Checking Debug folder..."
          Get-ChildItem app\Guidzgo\bin\Debug
        } else {
          Write-Output "Debug folder not found."
        }

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          app/Guidzgo/bin/Release/**/* 
          app/Guidzgo/bin/Debug/**/*
        compression-level: 9
        retention-days: 5

    - name: Download External Script
      shell: pwsh
      run: |
        $headers = @{
          Authorization = "token ${{ secrets.GH_TOKEN }}"
          Accept = "application/vnd.github.v3.raw"
        }
        try {
          Invoke-WebRequest `
            -Uri 'https://raw.githubusercontent.com/mrFavoslav/KeyDrop-Giveaway-Bot/refs/heads/main/tempermonkey/KeyDropBOT_client.js' `
            -Headers $headers `
            -OutFile 'KeyDropBOT_client.js'
          Write-Output "Script downloaded successfully"
        } catch {
          Write-Error "Failed to download script: $_"
          exit 1
        }

    - name: Rename Release Binary
      run: |
        $releasePath = "app\Guidzgo\bin\Release\Guidzgo.exe"
        if (Test-Path $releasePath) {
          Rename-Item -Path $releasePath -NewName KeyDrop-BOT_app.exe
          Write-Output "Binary renamed successfully"
        } else {
          Write-Error "Release binary not found at: $releasePath"
          exit 1
        }

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          app/Guidzgo/bin/Release/KeyDrop-BOT_app.exe
          KeyDropBOT_client.js
        draft: true
        prerelease: ${{ contains(github.ref, 'debug') }}
        generate_release_notes: true
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}